# Generated by Django 6.0.4 on 2026-04-26 10:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_scrapingjob_scrapingrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNeed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("fulfilled", "Fulfilled"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("countries", models.JSONField(blank=True, default=list)),
                (
                    "target_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_needs",
                        to="content.targetprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="content.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_need",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="idx_user_need_status"),
                    models.Index(fields=["user", "-created_at"], name="idx_user_need_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("preferred_domains", models.JSONField(blank=True, default=list)),
                ("preferred_countries", models.JSONField(blank=True, default=list)),
                ("notification_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="content.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="content.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="content.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_favorite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="idx_user_favorite_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "offer"),
                        name="uniq_user_favorite",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNeedDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_need_links",
                        to="content.domain",
                    ),
                ),
                (
                    "user_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_links",
                        to="content.userneed",
                    ),
                ),
            ],
            options={
                "db_table": "user_need_domain",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_need", "domain"),
                        name="uniq_user_need_domain",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="userneed",
            name="domains",
            field=models.ManyToManyField(
                related_name="user_needs",
                through="content.UserNeedDomain",
                to="content.domain",
            ),
        ),
        migrations.CreateModel(
            name="MatchingHit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("match_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("viewed", "Viewed"),
                            ("interested", "Interested"),
                            ("declined", "Declined"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_hits",
                        to="content.userneed",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_hits",
                        to="content.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_hits",
                        to="content.user",
                    ),
                ),
            ],
            options={
                "db_table": "matching_hit",
                "ordering": ["-match_score", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="idx_matching_hit_status"),
                    models.Index(fields=["user", "-match_score"], name="idx_matching_hit_score"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("need", "offer"),
                        name="uniq_matching_hit_need_offer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(match_score__gte=0)
                        & models.Q(match_score__lte=1),
                        name="matching_hit_score_range",
                    ),
                ],
            },
        ),
    ]
