# Generated by Django 6.0.4 on 2026-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_user_dashboard_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
