# Generated by Django 6.0.4 on 2026-04-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_crawlurl"),
        ("content", "0005_user_is_active"),
    ]

    operations = []
