# Generated by Django 6.0.4 on 2026-04-12 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'contact_role',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'domain',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('link', models.URLField(max_length=1000)),
                ('country', models.CharField(max_length=2)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'offer',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'offer_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'source_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'target_profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'oss_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'user_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_approved', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='content.contactrole')),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['contact_name'],
            },
        ),
        migrations.CreateModel(
            name='OfferContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_label', models.CharField(default='primary_contact', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contact')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.offer')),
            ],
            options={
                'db_table': 'offer_contact',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='contacts',
            field=models.ManyToManyField(related_name='offers', through='content.OfferContact', to='content.contact'),
        ),
        migrations.CreateModel(
            name='OfferDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.domain')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.offer')),
            ],
            options={
                'db_table': 'offer_domain',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='domains',
            field=models.ManyToManyField(related_name='offers', through='content.OfferDomain', to='content.domain'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='content.offertype'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('university', 'University'), ('company', 'Company'), ('other', 'Other')], max_length=30)),
                ('country', models.CharField(max_length=2)),
                ('website', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('country__regex', '^[A-Z]{2}$')), name='organization_country_iso2')],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='content.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='content.organization'),
        ),
        migrations.AddField(
            model_name='offer',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='content.sourcetype'),
        ),
        migrations.AddField(
            model_name='offer',
            name='target_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='content.targetprofile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offers', to='content.user'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_offers', to='content.user'),
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='content.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='content.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='content.userrole')),
            ],
            options={
                'db_table': 'user_organization',
            },
        ),
        migrations.AddConstraint(
            model_name='offercontact',
            constraint=models.UniqueConstraint(fields=('offer', 'contact'), name='uniq_offer_contact'),
        ),
        migrations.AddConstraint(
            model_name='offerdomain',
            constraint=models.UniqueConstraint(fields=('offer', 'domain'), name='uniq_offer_domain'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('link', 'organization'), name='uniq_offer_link_organization'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('country__regex', '^[A-Z]{2}$')), name='offer_country_iso2'),
        ),
        migrations.AddConstraint(
            model_name='userorganization',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'role'), name='uniq_user_org_role'),
        ),
    ]
