# Generated by Django 6.0.4 on 2026-04-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offer',
            name='uniq_offer_link_organization',
        ),
    ]
